import Header from "@/components/header";
import "../styles/globals.scss";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <Header />
                <main className="main">
                    <div className="main-bg"></div>
                    <div className="main-bg layer-1"></div>
                    <div className="main-bg layer-2"></div>
                    <div className="main-bg layer-3"></div>
                    {children}
                </main>
            </body>
        </html>
    );
}
